on:
  push:
    branches:
      - main

name: Documentation

jobs:
  build-docs:
    name: Deploy Noosphere Guide
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: 'Setup Rust'
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
      - name: 'Install Rust/WASM test dependencies'
        run: |
          rustup target install wasm32-unknown-unknown
          cargo install toml-cli
          WASM_BINDGEN_VERSION=`toml get ./Cargo.lock . | jq '.package | map(select(.name == "wasm-bindgen"))[0].version' | xargs echo`
          cargo install wasm-bindgen-cli --vers "$WASM_BINDGEN_VERSION"
          cargo install wasm-opt --locked
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: 'Build TypeScript packages'
        run: |
          cd ./typescript
          npm ci
          npm run build
          touch ./packages/noosphere-guide/_site/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./typescript/packages/noosphere-guide/_site
